# Generated by Django 2.0.7 on 2018-07-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VirtualMachine',
            new_name='DRBDAllocation',
        ),
    ]
